#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_SIDNEY      0
#define MUGSHOT_PHOEBE      1
#define MUGSHOT_GLACIA      2
#define MUGSHOT_DRAKE       3
#define MUGSHOT_CHAMPION    4
#define MUGSHOT_BRENDAN     5

#define MUGSHOTS_COUNT      6

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H